### ISSUE TITLE
junos.install_config state always reports success even if config.load fails

### ISSUE THREAD

**Issue by nembery** [Juniper/salt#41]
### Description of Issue/Question
The junos.install_config state always reports success (result=True) regardless of whether the underlaying config.load and commit actually succeed of fail. This is because the states/junos.py module hard codes the result value to be True. Trivial fix is to copy the value of ret['out'] to ret['result']. Otherwise, bubbling up an exception will also work.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Create a state file like the following
Install salt + a proxy minion to any junos device

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`
install_broken_config:
  junos.install_config:
    - path: salt://some_invalid_configuration_template.conf

report_succes:
  test.arg:
    - name: "This always works :-/"
    - require:
        - install_broken_config

report_failure:
  test.arg:
    - name: "This should get called when install_config fails"
    - onfail: 
        - install_broken_config
`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
All salt versions as of 2017.7.2

**Comment by eyalleshem** [comment]
+1.
 it's correct for all states - not only for install_config..  
see : https://github.com/saltstack/salt/blob/develop/salt/states/junos.py#L200 
It's initiate the the return value with {"result":True} . ad don't touch it where the function succeed or not.

**Comment by ksator** [comment]
+1

**Comment by vnitinv** [comment]
Fixed via #72
