### ISSUE TITLE
junos.install_config documentation is incorrect in state module

### ISSUE THREAD

**Issue by nembery** [Juniper/salt#42]
### Description of Issue/Question
The parameters names in the junos.install_config function in the state module is incorrect

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
n/a
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
check docs
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2017.7.2

**Comment by vnitinv** [comment]
@nembery Can you please specify the parameter in question.
