### ISSUE TITLE
add dry-run with junos modules.

### ISSUE THREAD

**Issue by ksator** [Juniper/salt#44]
### Description of enhancement
dry-run (test=True in salt) is a Salt features but not yet implemented with junos modules.

**Comment by msmihula** [comment]
+1 for dry run functionality using the Junos Salt module - this would be useful to me.

**Comment by ngrundler** [comment]
+1, this would be a very useful feature for us as well.  We are currently using the NAPALM modules with our junos devices as we can get a diff out of the device before applying the template from the same state without having to have separate load,diff,rollback process if we find some unexpected changes.

**Comment by wallywagon** [comment]
+1

**Comment by kris-steinhoff** [comment]
+1

**Comment by vnitinv** [comment]
Fixed via #81
