### ISSUE TITLE
add edit private option in junos modules

### ISSUE THREAD

**Issue by ksator** [Juniper/salt#46]
add edit private option in junos modules for SaltStack.

CLI and PyEZ has "edit exclusive" and 'edit private' options.
Ansible galaxy module juniper_junos_config support also "edit exclusive" and 'edit private' options (from galaxy module 2.0). 
Ansible core modules and SaltStack and Junos Space has only the "edit exclusive" option.

with "configure private" workflow, the configuration is not locked. So, no configuration lock error can happen. 
With a workflow that ensures a "single source of authority" for each section of their configuration, then a "configure private" workflow is the preferred workflow. 
Without a workflow that ensures a "single source of authority" for each section of their configuration, the "configure exclusive" workflow is preferred.

**Comment by eyalleshem** [comment]
+1

**Comment by rsmekala** [comment]
@ksator Isn't this already implemented in install_config method ??

https://github.com/Juniper/salt/blob/0148fe0de1697c803747aa15f36376daeb6a008b/salt/modules/junos.py#L751

```
 Optional
     * mode: The mode in which the configuration is locked.
       (Options: private, dynamic, batch, exclusive; default= exclusive)
```

Do you mean to say that it is currently not working or do you need the support of this option for any other module ??

**Comment by vnitinv** [comment]
@ksator  This feature is already present. closing the issue. Please re-open if you face any issue.
