### ISSUE TITLE
Commit happens on vSRX cluster but with  out=false

### ISSUE THREAD

**Issue by fahadkhan91** [Juniper/salt#47]
I am running salt "salt 2017.7.0-532-g79ee24c (Nitrogen)", trying to push config on a vSRX cluster.
Commit happens on vSRX cluster but with  "out=false"

sh-3.2# salt 'vsrx7' junos.install_config 'salt://config4.set' dev_timeout=300
vsrx7:
    ----------
    message:
        Commit check successful but commit failed with "RpcTimeoutError(host: 192.168.100.153, cmd: commit-configuration, timeout: 30)"
    out:
        False

OR

sh-3.2# salt 'vsrx7' junos.rollback 1
vsrx7:
    ----------
    message:
        Rollback successful but commit failed with error "RpcTimeoutError(host: 192.168.100.153, cmd: commit-configuration, timeout: 30)"
    out:
        False

**with state file:**

sh-3.2# cat install_config.sls
salt://config4.set:
  junos:
    - install_config
    - timeout: 300
    - template_vars:
        mx_name: mx_srx3

sh-3.2# salt 'vsrx7' state.apply install_config
vsrx7:
----------
          ID: salt://config4.set
    Function: junos.install_config
      Result: True
     Comment: 
     Started: 17:54:38.176811
    Duration: 39666.152 ms
     Changes:   
              ----------
              message:
                  Commit check successful but commit failed with "RpcTimeoutError(host: 192.168.100.153, cmd: commit-configuration, timeout: 30)"
              out:
                  False

Summary for vsrx7
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  39.666 s

how can we get rid of this wrong msg ?

Commit check successful but commit failed with "RpcTimeoutError(host: 192.168.100.153, cmd: commit-configuration, timeout: 30)"

**Comment by vnitinv** [comment]
@fahadkhan91 we have fixed the issue. will sync with upstream saltstack in coming days.

**Comment by vnitinv** [comment]
Should be fixed via #71 and #72
