### ISSUE TITLE
junos-execution-module should return success of or fail in "result" field and not in "out" field  

### ISSUE THREAD

**Issue by eyalleshem** [Juniper/salt#60]
It's critical - because  the state "module.run" treat the execution of sucsess/failed according this field. 
It's more crtical as the junos-state currentlly do not report success or fail 
see issue : #41 

temporary workaround that i use  : 
a custom junos_helper module that set the function results in "result" 
https://gist.github.com/eyalleshem/204af4bc8fbb04d6c11c5ab63cc539c7

**Comment by vnitinv** [comment]
Fixed via #72
