### ISSUE TITLE
junos.rpc state is broken in 2018.3.3

### ISSUE THREAD

**Issue by rsmekala** [Juniper/salt#77]
### Description of Issue/Question
Salt made some documentation changes in 2018.3.3 breaking the state module

Salt commit:https://github.com/saltstack/salt/commit/93ee5ee2b01b6f752f5538d0da413719d410d65c#diff-15ad308a12ea5b6d5188dd4a94eab4a0

**Comment by vnitinv** [comment]
Fixed via #81
