### ISSUE TITLE
install_config times out on longer commit checks

### ISSUE THREAD

**Issue by AlpineScrewdriver** [Juniper/salt#85]
Using new timeoutdecorator still doesn't fix install_config for me when commit_check takes 30+ seconds as well. Looks like timeout is set temporarily for certain tasks but not the commit check.

The only way I can get longer device commits to work (that take +30 seconds to commit check as well) is to modify the device.py itself to hard code the timeout property to 300, then restarting the proxy-minion.

I would recommend testing anything timeout related with an SRX300. You can use a state with a configuration group of ~10 items (doesn't need to be enormous) and applying that group. You will want to make sure a commit check on the device itself takes longer than 30 seconds for what the state is trying to apply.

10 security address objects or 10 dhcp bindings should do the trick.

A better approach to this in general would be to start the proxy minion with an RPC timeout option to override the default of 30.
Something like:
"salt-proxy --proxyid=SLOWSRX -d -t 300"

If commit checks are timing out these might show up in install_config as unlockerrors or rpctimeouts from my testing.

edit: timeout support would make more sense in proxy data in the pillar
   timeout: 300   (would be amazing)

**Comment by rsmekala** [comment]
@Zapotomous Could you please provide the following details.
* What branch of the repository are you currently using ??
Example :  
```
git branch
* 2018.3.3
  develop
  updated_develop
```
* What is the salt command you are trying to run ??
Example:
`salt 'device_name' junos.install_config 'salt://config.set' dev_timeout=300`

**Comment by AlpineScrewdriver** [comment]
I pulled down the updated_develop branch again and can't reproduce the issue I was having before where dev_timeout would not work. I've tested passing dev_timeout to rollback and install_config several times with no issues now.

Thanks for opening a task for pillar option timeout.
